

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"  # Changed left port to avoid conflict with old project
      - "15673:15672" # Changed left port to avoid conflict with old project
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  express:
    build: .
    container_name: ticket-support-express-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - rabbitmq

    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # or `npm run start` depending on your setup
